server:
  port: 8003
spring:
  application:
    name: gateway-service
#  grpc:
#    server:
#      port: 9003
  grpc:
    client:
      channels:
        consultaVeiculoService:
          address: static://192.168.100.75:9004